name: BetterMechanics
main: net.edoxile.bettermechanics.BetterMechanics
version: 1.13
authors: ['Edoxile', 'GuntherDW']
website: https://github.com/Edoxile/BetterMechanics
commands:
    pen:
        description: Change the text of signs
        usage: /pen [clear|set|setline|help]
        aliases: p
    bettermechanics:
        description: Change the text of signs
        usage: /bettermechanics reload <cauldron>
        aliases: bm